import { Project, TechCategory } from "../types"

export const techStack: TechCategory[] = [
  {
    title: 'Frontend',
    items: [
      { name: 'HTML5', color: 'from-orange-500 to-red-500' },
      { name: 'CSS3', color: 'from-blue-500 to-cyan-500' },
      { name: 'JavaScript', color: 'from-yellow-400 to-orange-500' },
      { name: 'TypeScript', color: 'from-blue-600 to-blue-800' },
      { name: 'React', color: 'from-cyan-400 to-blue-500' },
      { name: 'Next.js', color: 'from-gray-600 to-gray-900' },
      { name: 'Tailwind CSS', color: 'from-teal-400 to-cyan-600' },
      { name: 'Bootstrap', color: 'from-purple-500 to-purple-700' },
      { name: 'Framer Motion', color: 'from-pink-500 to-purple-600' },
      { name: 'PWA', color: 'from-indigo-500 to-blue-700' },
    ],
  },
  {
    title: 'Backend',
    items: [
      { name: 'Node.js', color: 'from-green-500 to-emerald-600' },
      { name: 'Express.js', color: 'from-gray-500 to-gray-700' },
      { name: 'REST APIs', color: 'from-indigo-500 to-blue-600' },
      { name: 'JWT Auth', color: 'from-rose-500 to-red-600' },
      { name: 'node-cron', color: 'from-slate-500 to-gray-700' },
      { name: 'Server-Sent Events', color: 'from-cyan-500 to-teal-600' },
      { name: 'Nodemailer', color: 'from-yellow-500 to-amber-600' },
    ],
  },
  {
    title: 'Integrations & Automation',
    items: [
      { name: 'Freshsales API', color: 'from-green-500 to-teal-600' },
      { name: 'Freshmarketer', color: 'from-teal-500 to-green-600' },
      { name: 'Twilio', color: 'from-red-500 to-rose-600' },
      { name: 'SendGrid', color: 'from-blue-500 to-sky-600' },
      { name: 'Webhooks', color: 'from-violet-500 to-purple-700' },
      { name: 'Web Push', color: 'from-fuchsia-500 to-pink-600' },
      { name: 'Google Sheets API', color: 'from-emerald-500 to-green-600' },
    ],
  },
  {
    title: 'Database & Cloud',
    items: [
      { name: 'MongoDB', color: 'from-green-600 to-green-800' },
      { name: 'Mongoose', color: 'from-red-500 to-red-700' },
      { name: 'Firebase', color: 'from-yellow-500 to-orange-600' },
      { name: 'Cloudinary', color: 'from-blue-400 to-blue-600' },
    ],
  },
  {
    title: 'Tools & Platforms',
    items: [
      { name: 'Git & GitHub', color: 'from-gray-700 to-gray-900' },
      { name: 'Vercel', color: 'from-gray-600 to-black' },
      { name: 'Stripe', color: 'from-violet-500 to-indigo-600' },
      { name: 'VS Code', color: 'from-blue-500 to-blue-700' },
    ],
  },
]

export const projects: Project[] = [
  {
    slug: 'harmony-garden',
    title: 'Harmony Garden — Growth & Operations Platform',
    subtitle: 'CRM-integrated systems for a real estate company\'s full lead-to-close pipeline',
    summary: 'A suite of four connected systems handling lead capture, nurture, sales-pipeline analytics, and internal operations — integrated across Freshsales, Freshmarketer, SendGrid, and Twilio.',
    category: 'Systems & Integrations',
    tech: ['Next.js', 'Node.js', 'MongoDB', 'Freshsales API', 'Freshmarketer', 'Twilio', 'SendGrid', 'Webhooks'],
    image: '/images/harmony-garden-cover.svg',
    featured: true,
    flagship: true,
    order: 1,
  },
  {
    slug: 'campaign-engine',
    parent: 'harmony-garden',
    title: 'Email Campaign Engine',
    summary: '5 sender identities, 9 templates, 56,000+ leads managed with daily automated sends, tracking, and analytics.',
    category: 'Systems & Integrations',
    tech: ['Node.js', 'Express', 'MongoDB', 'SendGrid', 'node-cron'],
    image: '/images/harmony-campaign-engine.svg',
    featured: false,
    order: 2,
  },
  {
    slug: 'sms-nurture',
    parent: 'harmony-garden',
    title: 'SMS + Email Nurture System',
    summary: 'A 24-week automated drip sequence across SMS and email with a live, real-time dashboard powered by Server-Sent Events.',
    category: 'Systems & Integrations',
    tech: ['Node.js', 'Twilio', 'SendGrid', 'Server-Sent Events', 'MongoDB', 'node-cron'],
    image: '/images/harmony-sms-nurture.svg',
    featured: false,
    order: 3,
  },
  {
    slug: 'kpi-dashboard',
    parent: 'harmony-garden',
    title: 'Sales Pipeline KPI Dashboard',
    summary: 'A multi-stage sales pipeline dashboard reading live from Freshsales, embedded directly inside Freshsales as an iframe widget.',
    category: 'Systems & Integrations',
    tech: ['Node.js', 'Express', 'Freshsales API'],
    image: '/images/harmony-kpi-dashboard.svg',
    featured: false,
    order: 4,
  },
  {
    slug: 'galadima',
    parent: 'harmony-garden',
    title: 'Galadima — Internal Operations Platform',
    summary: 'Employee management, KPI/appraisal scoring, role-based access, audit logs, and a rule engine routing webhook events from three different platforms into real-time push notifications.',
    category: 'Systems & Integrations',
    tech: ['Next.js', 'TypeScript', 'MongoDB', 'PWA', 'Web Push', 'JWT Auth', 'Cloudinary', 'Google Sheets API'],
    image: '/images/harmony-galadima.svg',
    featured: false,
    order: 5,
  },
  {
    slug: 'cornerstone-catering',
    title: 'Cornerstone Catering Services',
    summary: 'A full-stack Nigerian food ordering platform for a real catering business serving Chicago and Minnesota — Stripe checkout, admin dashboard, live order tracking, automated email notifications.',
    category: 'Full-Stack',
    tech: ['Next.js', 'TypeScript', 'MongoDB', 'Stripe', 'Tailwind CSS', 'Cloudinary', 'Nodemailer'],
    image: '/images/cornerstone.png',
    github: 'https://github.com/boluwatifemi23/my-fullstack-app',
    live: 'https://cornerstonecatering.vercel.app',
    featured: true,
    order: 10,
  },
  {
    slug: 'parentcircle',
    title: 'ParentCircle — Social Platform',
    summary: 'A social networking platform for parents — feeds, milestone tracking, testimonials, community gallery, full onboarding flow.',
    category: 'Full-Stack',
    tech: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    image: '/images/parentcircle.png',
    github: 'https://github.com/boluwatifemi23/mylevel4project',
    live: 'https://mylevel4project.vercel.app',
    featured: true,
    order: 11,
  },
  {
    slug: 'swiftfunds',
    title: 'SwiftFunds — Digital Banking App',
    summary: 'A working fintech app with real Firebase auth and a banking dashboard mirroring modern Nigerian digital finance UX.',
    category: 'Frontend',
    tech: ['JavaScript', 'HTML5', 'CSS3', 'Firebase'],
    image: '/images/swiftfundsimage.jpeg',
    github: 'https://github.com/boluwatifemi23',
    live: 'https://myproject-f2fed.web.app/',
    featured: true,
    order: 12,
  },
  {
    slug: 'neontech',
    title: 'NeonTech — Cyberpunk Landing Page',
    summary: 'Pure CSS neon glow effects, particle systems, and glitch animations — no JS framework.',
    category: 'Frontend',
    tech: ['HTML5', 'CSS3'],
    image: '/images/neon-tech.png',
    github: 'https://github.com/boluwatifemi23/neotech',
    live: 'https://neon-tech-ivory.vercel.app/',
    featured: false,
    order: 20,
  },
  {
    slug: 'luxe',
    title: 'Luxe — Premium Glassmorphism Showcase',
    summary: 'Glassmorphism UI with 3D card tilt interactions and animated gradients.',
    category: 'Frontend',
    tech: ['HTML5', 'CSS3', 'Bootstrap', 'JavaScript'],
    image: '/images/luxe.png',
    github: 'https://github.com/boluwatifemi23/luxelandingpage',
    live: 'https://luxelandingpage.vercel.app/',
    featured: false,
    order: 21,
  },
  {
    slug: 'nexus',
    title: 'Nexus — SaaS Landing Page',
    summary: 'A full SaaS marketing site built entirely with Tailwind utility classes.',
    category: 'Frontend',
    tech: ['HTML5', 'Tailwind CSS', 'JavaScript'],
    image: '/images/nexus.png',
    github: 'https://github.com/boluwatifemi23/nexus',
    live: 'https://nexus-orcin-kappa.vercel.app/',
    featured: false,
    order: 22,
  },
  {
    slug: 'taskmaster',
    title: 'TaskMaster — Vanilla JS Task Manager',
    summary: 'Zero-framework task manager with class-based OOP, drag-and-drop, and localStorage persistence.',
    category: 'Frontend',
    tech: ['JavaScript', 'HTML5', 'CSS3'],
    image: '/images/taskmasterrr.png',
    github: 'https://github.com/boluwatifemi23/taskmaster',
    live: 'https://taskmaster-indol-five.vercel.app/',
    featured: false,
    order: 23,
  },
]

export const navItems = [
  { name: 'Home', href: 'home' },
  { name: 'About', href: 'about' },
  { name: 'Skills', href: 'skills' },
  { name: 'Projects', href: 'projects' },
  { name: 'Contact', href: 'contact' },
]